.TH MDVIEW 1 "December\ 19,\ 2004"
.SH 名称
mdview \- 各種の分子集団をX windowに3Dで表示する
.SH 書式
.B mdview [
.I Options...
.B ]
.I DataFile
.SH 解説
mdviewは各種分子集団(MD trajectory など)をX windowに
3Dで表示します。データファイルには、それぞれの原子の座標
のみを用意すれば良く、原子間の結合は、結合距離を引数で設定
すると、mdviewが計算して画面に表示します。視点を変更した
り、画像を拡大、縮小できます。連続したデータをアニメーショ
ンで見ることができます。また、スナップショットをPOV-Ray
用のファイルに変換することができます。
.SS オプション
.PP
オプション引数には、以下のものが利用できます。このうち、
.B \-format
あるいは
.B \-format-
オプションは、いずれかが必ず1度以上
出現する必要があります。両立しないオプションを両方指定した
場合は、後に書いたものが有効になります。これらのオプション
引数を頻繁に利用する場合は、引数ファイルを利用すると便利です。 
.TP
.B \-ang
以降の引数やデータファイルの単位系を、オングストロームとみなして
処理します(cf.
.B \-au
)
.TP
.BI \-arg\  Version
引数のバージョンを指定します。
3.23で、
.B \-bond
オプション、3.60で、
.B \-bond
,
.B \-count
オプションの動作が変わります。defaultは
.I 3.00
です。
.TP
\fB\-atom \fIName Mass Radius Color\fR
原子の情報を登録、または変更します。
.I Name
は原子名です。大文字で始まり、任意の数だけ小文字を続けます。
(O H Na Osc などはOKです。ATOM H+ などは使えません。)
.I Mass
は質量です。適当な単位系で入れて下さい。
(defaultの設定ファイルは
.I amu
を使っています。)
.I Radius
は半径です。そのときの(
.B \-au
,
.B \-ang
)と同じ単位系で受け付けます。
.I Color
は色です。文字列で色の名前を指定して下さい
(rgb.txt参照)。16進表記(#FF00FFなど)も可能で
す。現在は全て指定しないといけないので、上書きによ
る変更は大変です。
.TP
.BI \-atom-\  Name
原子
.I Name
に関する全ての設定を取り消します。
.TP
.B \-au
以降の引数やデータファイルの単位系を、atomic unit
とみなして処理します。これがdefaultです。 (cf. 
.B \-ang
)
.TP
.BI \-bg\  Color
ウィンドウの背景の色を設定します。defaultは
\fB\-bg \fIblack\fR
です。
.TP
.B \-blank_line
アスキー形式のデータファイルで、空行をステップの区切りとして
処理します。
.B \-blank_line-
に比べて、動作が高速です。
.TP
.B \-blank_line-
アスキー形式のデータファイルで、空行をステップの区切りとして
処理しません。これがdefaultです。
.TP
\fB\-bond \fIName-Name Length Color \fR(Ver.3.00)
.PD 0
.TP
\fB\-bond \fIName-Name Length Radius Color \fR(Ver.3.23)
.PD 0
.TP
\fB\-bond \fIName-Name Length Name \fR(Ver.3.60)
.PD
1つめの
.I Name
と2つめの
.I Name
であらわされる(登録
されている)原子どうしの結合を登録、または変更し
す。結合は原子名どうしをハイフンで結びます。 このハ
イフンの数は可変になっていて、数が多いほど距離の長
い結合をあらわします。
.I Length
は結合距離で、原子間
の距離がこれ以下になると結合を作ります。 単位はその
時有効なオプション(
.B \-au
,
.B \-ang
)に従います。以後の引数は、引数のバージョン(
.B \-ang
)に従って異なります。
.I Color
は色です。指定方法は
.B \-atom
と同様です。
.I Radius
は、結合の太さ(円筒の半径)です。この値は、
現在はPOV-Ray出力にのみ反映されます。3つめの
.I Name
は、
.B \-bond_shape
で指定する結合の形状の名前です。
.TP
.BI \-bond-\  Name-Name
結合
.I Name-Name
に関する全ての設定を取り消します。
.TP
\fB\-bond_shape \fIName Radius Color\fR
.PD
結合の形状
.I Name
を登録、または変更します。
.I Radius
は、結合の太さ(円筒の半径)です。この値は、現在は
POV-Ray出力ににのみ反映されます。
.I Color
は色です。指定方法は
.B \-atom
と同様です。
.TP
.B \-c
.PD 0
.TP
.B \-clear
.PD
原子の輪郭を表示するようにします。 多少ですが遅くな
ります。
.TP
.B \-c-
.PD 0
.TP
.B \-clear-
.PD
原子の輪郭を表示しません。 これがdefaultです。
.TP
\fB\-center \fIX Y Z\fR
画面の中心を、重心の代わりに(
.I X
,
.I Y
,
.I Z
)に設定し
ます。
.TP
.B \-center-
画面の中心を、重心に設定します。これがdefaultで
す。
.TP
.BI \-color\  Level
奥行きを表現するためにどの程度多くの色を使うかを設
定します。
.I Level
は
.I 0
から
.I 9
まで選択できます。値が
大きいほどなめらかにグラデーションがかかります。
default は
.I 1
です。
.TP
\fB\-count \fIName Name- Total Color_L Color_H \fR(Ver.3.00)
.PD 0
.TP
\fB\-count \fIName Total Color_L Color_H \fR(Ver.3.60)
.PD
ある原子の、特定の結合の数を数え、
.I Total
より少ない
時に
.I Color_L
、多い時に
.I Color_H
で表示するようにしま
す。
.TP
.BI \-count-\  Name
原子
.I Name
に関する
.B -count
の設定を取り消します。
.TP
\fB\-count_n \fIName Name Count\fR
.PD
1つめの
.I Name
で表される原子について、2つめの
.I Name
で表される結合形状を、
.I Count
だけ数えます。
.TP
.BI \-d\  Number
どれだけ離れた所から見るか、その距離を入力します。
数値は第1ステップの集団の半径の何倍とするかを入力
します。defaultは
.I 10
です。値が小さいほど立体感
が増します。大きいほど各原子の距離感が正確になりま
す。
.TP
\fB\-e \fITheta Psi Phi\fR
.PD 0
.TP
\fB\-euler \fITheta Psi Phi\fR
.PD
最初の表示角度をオイラー角で指定します。この引数に
続けて
.I Theta
、
.I Psi
、
.I Phi
の順でdegree単位(一周が360度)
で整数で入力して下さい。defaultは全て
.I 0
で、z軸方
向から眺めます。(画面ではx軸が右、y軸が上、z軸
が手前方向になっています。)
.TP
.BI \-f\  FileName
引数ファイル
.I FileName
を読み込みます。
.TP
.BI \-frame\  Number
1秒間に最大何フレーム表示するかを設定します。設定
値は
.I 8
,
.I 10
,
.I 12
,
.I 15
,
.I 24
,
.I 30
,
.I 0
のみ指定できます。
.I 0
は無制限を意味します。 defaultは
.I 0
です。
.TP
.B \-fold
周期境界条件を使っている場合に、 自動的にデータの折
り返しをするようになります。
.TP
.B \-fold-
上述の
.B -fold
の自動折り返し機能を使用しません。 これ
がdefaultです。
.TP
\fB\-format \fIString
データファイルがどのような書式であるかを設定しま
す。具体的には、何番目の原子が何であるか、の対応を
分子式に似た文字列で定義します。例えば、
.nf
    \-format\  CH4
.fi
なら、1番目がC原子、以降2から4番目がH原子
の順になります。データファイルには、この順番で座標
を並べて下さい。(便利かどうかはわかりませんが)次の
ような複雑な設定もできます。
.nf
    \-format\  '(NH2)2CO'
.fi
この例では、NHHNHHCOの順になります。(シングルクォ
ートでくくるのは、小括弧の特別な意味を取り除くた
め。)また、原子や分子の数がデータファイルごとに異
なっている場合でも同じ
.B \-format
の設定を利用できるよ
うに、繰り返し回数に変数が使えるようになっていま
す。 変数名は小文字1文字です。以下のように四則演算
も可能です。
.nf
    \-format\  'C(n)H(2n+2)'
.fi
この場合、nに3を指定すると、C3H8と解釈されま
す。(変数の値の指定は、引数の最後のデータファイルの
直前で行ないます。)ただし、これらの変数は整数しか
扱えません。値は、最終的に原子のくり返し回数が0以
上になるようにしてください。
.TP
.B \-format-
拡張データファイルを利用します。
.TP
.B \-help
.PD 0
.TP
.B --help
.PD
引数のヘルプを出して、終了します。
.TP
.BI \-layer\   "Name NumberList"
レイヤーの名前とそれに属する原子を登録します。
\'NumberList'の詳しい書式は下にあります。
.TP
.BI \-layer-\   Name 
名前が
.I Name
のレイヤーを消します。
.TP
.B  \-layer_kill
全てのレイヤーを消去します。
.TP
.BI \-length\  Length
.PD 0
.TP
.BI \-length\  '(X,Y,Z)'
.TP
.BI \-length\  '(XX,XY,XZ,YX,YY,YZ,ZX,ZY,ZZ)'
.PD
周期境界条件を設定します。
最初が、一辺の長さ
.I Length
の立方体を、次が、x軸の長さ
.I X
、y軸の長さ
.I Y
、z軸の長さ
.I Z
の直方体を、最後がベクトル
.I (XX, XY, XZ)
、
.I (YX, YY, YZ)
、
.I (ZX, ZY, ZZ)
を各辺とする平行六面体を周期境界セルとします。
いずれかに
.I 0
を指定すると、その軸は周期境界を持ちません。 
.TP
.B \-length-
周期境界条件を取り除きます。つまりクラスターとして
扱います。これがdefaultです。
.TP
.B \-loop
ステップ全体の前後を繋いで、繰り返し再生します。
.TP
.B \-loop-
繰り返し再生しません。
これがdefaultです。
.TP
.BI \-max\  Particles
.B \-format-
オプション利用時に扱える粒子数の上限を設定
します。
.I 0
は無制限を意味します。defaultは
.I 0
です。
.TP
.BI \-mark\  Color
画面で[Mark]ボタンを利用したり、pコマンドを数字
に続けて使用した際に、その数字番目の原子を
.I Color
色で表示します。(番号は、入力データの粒子の順番と同じ
です。)
.TP
.B \-multi
粒子のマークを複数可能にします。
.TP
.B \-multi-
粒子のマークを排他的にします。 これがdefaultです。
.TP
.BI \-povray\  Version
POV-Rayのバージョン番号を指定します。
defaultは
.I 3.0
です。
.TP
.BI \-range\  Length
表示範囲を指定します。
.I 0
を指定した場合は入力されたデータから自動調節します。 defaultは
.I 0
です。
.TP
.B \-version
.PD 0
.TP
.B --version
.PD
バージョン情報を出力して終了します。
.TP
.BI \-visible\  Name[,Name[,...]]
.I NumbeList
で指定されたレイヤーを可視状態にします。それ以外のレイヤーは不可視状態
となります。
\'NumberList'の詳しい書式は下にあります。
.TP
.BI \-w\  Number
.PD 0
.TP
.BI \-window\  Number
.PD
表示するwindowのsizeを入力します。 defaultは
.I 400
です。
.SS GTK,GDKオプション
GTK,GDKに固有のオプションを有効にしています。
必要があればご利用下さい。これらは引数ファイルに記述す
ることはできません。 
.TP
.BI --display\  host:dpy
remote hostの画面に表示します。defaultは
.I $DISPLAY
です。
.SS 引数ファイル
引数ファイルとは、コマンドラインに記述する引数を そのままファイルに
書き出したものです。
.B \-f
オプションに続けてファイル名を記述することで、ファイルに書かれた
引数が全て
.B mdview
に読み込まれます。
.sp
基本的には引数をそのまま書き出せば使えますが、 読みやすくするために
コマンドラインの定義からいくつかの変更があります。 
.IP o
ファイルでの改行、タブ文字はただの空白と見なされます。
.IP o
バックスラッシュ(or円記号) \ は次の文字から特殊な意味を奪い、
ただの文字にします。
.IP o
シングルクォート ' で囲まれた文字はただの文字になります。
(例外は改行文字だけです。) 
.IP o
シャープ # 以降は改行までがコメントアウトされます。 
.IP o
漢字はコメントにのみ使用できます。
.IP o
^Lなどのコントロール文字も基本的に禁止です。 (DOSで書いたファイルを
持ち込んだりすると^Mやら^Zやらがつきますが、 これもダメです。) 
.IP o
次の文字はコマンドラインでは特殊な意味をもつので、 バックスラッシュ
などを用いて文字化しない限り、 コメント以外では使用できません。
.sp
" ( ) ? * < > | & ; ` ! $ ~
.PP
最初の引数で引数ファイルが指定されていない場合には default
の設定が用いられます。カレントまたはホームディレクトリに
.I \&.mdviewrc
、または
.I mdview.arg
という名のファイルがあれば、
それを読みます。それも存在しない場合は、システム保有の設定
(defaultでは
.I /usr/local/share/mdview/mdviewrc
)を読みま
す。(defaultでは水分子用の設定がされています。必要に応じ
て変更してください。) 
.sp
引数の途中で
.B \-f
オプションを用いることで引数ファイルを追加
読み込みできます。また、ファイル内で
.B \-f
オプションを使うこ
とも可能です。 
.SS NumberListの書式
数字列はカンマで区切ります。
もし、1と2と3のような連続した数字列を記述したいならば、
ハイフンを使って1-3のように記述することも可能です。
余分な空白文字は許容されますが、クォーテーションでくくる必要が
あるかも知れません。
例えば、1, 3, 4, 7, 8, 9, 10を記述したいならば、
.sp
.nf
      1,3,4,7,8,9,10
.fi
.sp
あるいは
.sp
.nf
      1,3,4,7-10
.fi
.sp
と記述します。
.I NumberList
の最初の数字は0ではなく、1です。
.SS データファイル
データファイルには、原子の座標データのみをx,y,z軸の順で記述します。
このため、座標と原子の対応を
.B \-format
オプションで指定する必要があります。 
.sp
ファイルの形式には、アスキーとFORTRANのUNFORMATTED 形式が利用できます。
粒子数はメモリの許す範囲内で自由です。
.sp
アスキー形式では、1行に1原子の座標をx,y,z座標の順で、 空白文字で
区切って並べて下さい。 複数ステップある場合は、同様に続けて記述します。
#を書くと、改行までがコメントアウトされます。
書いたコメントは
.B [Info]
ウィンドウで表示することができます。
.sp
また、FORTRANのUNFORMATTED形式の場合、
.sp
.nf
    double precision x(n),y(n),z(n)
    write(num) x,y,z
.fi
.sp
のように1レコードに1ステップ分の座標データをdouble precision
(8バイト浮動小数点数)配列で x,y,z座標の順で並べてください。
各配列の要素には、アスキー形式と同様の原子の順番で並べます。
複数ステップある場合は、同様に続けて記述します。 
.SS 拡張データファイル
拡張データファイルは、それぞれのステップごとに、 原子の数や
種類を変化できるようにしたものです。 利用するためには
.B \-format-
オプションを指定する必要があります。
1ステップ分のデータは、アスキー形式で以下のように記述します。 
.sp
.nf
    (引数) (...)
    (1ステップ分の粒子の数)
    (原子名) (x座標) (y座標) (z座標)
    \&...粒子の数だけ繰り返す
.fi
.sp
また、
.B \-bond_shape
を用いて結合の形状を指定してある場合、以下のようにして
拡張データの内部に結合の情報を記述することができます。
.sp
.nf
    (引数 ...)
    (1ステップ分の粒子の数) (1ステップ分の結合の数)
    (原子名) (x座標) (y座標) (z座標)
    ...粒子の数だけ繰り返す
    (結合形状名) (原子の番号) (原子の番号)
    \&...結合の数だけ繰り返す
.fi
.sp
粒子数は
.B \-max
オプションで指定された値が上限になります。複数ステップある
場合は、同様に続けて記述します。 また、#を書くと、
改行までがコメントアウトされます。書いたコメントは
.B [Info]
ウィンドウで表示することができます。
.sp
引数は、引数ファイルで記述するものと書式、機能は同じです。
以下のものが利用可能です。これらは、ファイルから読まれる
度に常に現在の状態を上書きします。
.sp
.B \-au, \-ang, \-center, \-center-, \-d, \-euler, \-fold, \-fold-,
.B \-length, \-length-, \-range
.SS 操作方法
.B mdview
はマウスとキーボードによる操作が行えます。 
.sp
マウス操作に関しては、文章での説明は困難なので、一般的な操作に
ついては省略して、少し特殊な操作のみ解説します。 
.PP
(粒子を表示するウィンドウ内で)
.TP
左ドラッグ: 
見る範囲を並進して変更します。(Translation時)
.sp
分子集団を回転します。(Rotation時) 
.TP
左ダブルクリック: 
見る範囲を原点に戻します。(Translation時)
.sp
回転角度を初期状態に戻します。(Rotation時) 
.TP
中央クリック: 
粒子をマーク/マーク解除します。 
.TP
右クリック: 
マウスカーソルの指している粒子の情報を表示します。(番号、xyz座標) 
.PP
キーボード入力に関しては以下の通りです。
*印をつけたコマンドは、 数字の後に続けて入力することができます。
.RS
.TP
.B j +
*1step進む。
.TP
.B k \-
*1step戻る。
.TP
.B f SPACE
*25step続けて進む。
.TP
.B b
*25step続けて戻る。
.TP
.B e / s
最後まで続けて進む/最初まで続けて戻る。
.TP
.B g / G
*最初/最後(数字があればそのステップ)まで移動する。
.TP
.B z / Z
縮小/拡大する。
.TP
.B a / d / w / x
左側/右側/上側/下側に1度回転する。(大文字なら10度)
.TP
.B t
一回転する。
.TP
.B %
*数字％に拡大、縮小する。
.TP
.B p
*数字番目の原子に印をつける。
.TP
.B v
*数字番目の原子が中央に来るように視点を動かす。
.TP
.B V
印のついた原子が中央に来るように視点を動かす。
.TP
.B o
*数字番目の原子を原点とする。
.TP
.B q Q
終了する。
.RE
.PP
また、Ctrl-cで実行中の動作を中止することができます。
.SS POV-Rayファイルへのコンバート
ウィンドウ上にある
.B [Convert]
ボタンを押すことで、そのとき表示されている画像をレイトレーサー
.I POV-Ray
が扱えるファイルとして記録することができます。
.sp
コンバート時に、
.I *.pov
ファイルと
.I *.inc
ファイルを生成します。
.I *.inc
ファイルは、ある程度再利用性がある部分 (見栄えを調整するために必要な
情報)を
.I *.pov
から抽出したもので、 カスタマイズされて多数回利用されることを
想定しています。(同じ原子、結合、色の設定を用いるなら、 formatが違っても
.I *.inc
ファイルを共有できます。) 
.sp
実際に
.I test.pov
というファイルをレイトレースする場合、 入力はこのようになります。(
.I *.inc
ファイルは自動的に読まれます。) 
.sp
.nf
povray +D0 +P +X +A +W400 +H400 +Itest.pov
.fi
.sp
また、
.I *.pov
ファイルに書かれる座標データR??の数値は、入力ファイルの値そのまま
になっています。
.I POV-Ray
出力を修正する場合に参考にして下さい。
.SH 環境変数
.TP
.B DISPLAY
ここで設定されたディスプレイに表示します。
.B \-display
オプションが設定されていれば、そちらが優先されます。
.SH 制限事項
.IP o
登録できる結合のハイフンの長さは最大256です。
.IP o
表示できる結合の数は、一つの原子あたり8本までです。
.SH 関連ファイル
.I \&./\&.mdviewrc
.br
.I \&./mdview.arg
.br
.I ${HOME}/\&.mdviewrc
.br
.I ${HOME}/mdview.arg
.br
.I /usr/local/share/mdview/mdviewrc
.SH 著作権
.B mdview
のソースファイル、および本ドキュメントファイルに関して、
作者である馬場 昭典 (akinori@kobe-u.ac.jp) が著作権を所有します。
.B mdview
はフリーソフトウェアであり、誰もが無償で利用できます。
パッケージの再配布、ソースの改変は自由です。 
.SH 著者
馬場 昭典(akinori@kobe-u.ac.jp)
.br
岩橋 建輔(iwahashi@ims.ac.jp)
.SH 関連項目
povray(1)
